import { cn } from '@/lib/utils';
import {
	AlarmClockIcon,
	AlbumIcon,
	AmbulanceIcon,
	AmphoraIcon,
	AnchorIcon,
	AntennaIcon,
	AnvilIcon,
	AppleIcon,
	ArchiveIcon,
	AwardIcon,
	AxeIcon,
	BabyIcon,
	BackpackIcon,
	BananaIcon,
	BandageIcon,
	BanknoteIcon,
	BathIcon,
	BeanIcon,
	BedIcon,
	BeefIcon,
	BeerIcon,
	BicepsFlexedIcon,
	BikeIcon,
	BinocularsIcon,
	BirdIcon,
	BookIcon,
	BoomBoxIcon,
	BowArrowIcon,
	BoxIcon,
	BrainIcon,
	BriefcaseIcon,
	BrushCleaningIcon,
	BrushIcon,
	BubblesIcon,
	BugIcon,
	BuildingIcon,
	BusIcon,
	CableIcon,
	CakeIcon,
	CalculatorIcon,
	CameraIcon,
	CandyCaneIcon,
	CandyIcon,
	CaravanIcon,
	CarFrontIcon,
	CarIcon,
	CarrotIcon,
	CastleIcon,
	CatIcon,
	ChefHatIcon,
	CherryIcon,
	ChurchIcon,
	CigaretteIcon,
	CircleDashedIcon,
	CitrusIcon,
	ClapperboardIcon,
	ClipboardIcon,
	ClockIcon,
	CloudIcon,
	CloverIcon,
	CoffeeIcon,
	CookieIcon,
	CroissantIcon,
	DogIcon,
	DoorClosedIcon,
	DramaIcon,
	DrillIcon,
	DrumIcon,
	DrumstickIcon,
	DumbbellIcon,
	EarthIcon,
	EllipsisIcon,
	FuelIcon,
	Gamepad2Icon,
	GhostIcon,
	GiftIcon,
	GlassWaterIcon,
	GuitarIcon,
	HamburgerIcon,
	HamIcon,
	HammerIcon,
	HatGlassesIcon,
	HeadphonesIcon,
	HeartIcon,
	HospitalIcon,
	HotelIcon,
	HouseIcon,
	IceCreamConeIcon,
	LampIcon,
	LaptopIcon,
	LeafIcon,
	LightbulbIcon,
	MartiniIcon,
	MedalIcon,
	MountainSnowIcon,
	NewspaperIcon,
	PackageIcon,
	PaintbrushIcon,
	PaletteIcon,
	PartyPopperIcon,
	PawPrintIcon,
	PhoneIcon,
	PianoIcon,
	PickaxeIcon,
	PiggyBankIcon,
	PizzaIcon,
	PlaneIcon,
	PocketKnifeIcon,
	PopcornIcon,
	PopsicleIcon,
	PrinterIcon,
	PuzzleIcon,
	RabbitIcon,
	RatIcon,
	ReceiptTextIcon,
	RocketIcon,
	RockingChairIcon,
	RollerCoasterIcon,
	SailboatIcon,
	SaladIcon,
	SandwichIcon,
	ShipIcon,
	ShirtIcon,
	ShoppingBagIcon,
	ShoppingBasketIcon,
	ShoppingCartIcon,
	ShovelIcon,
	ShowerHeadIcon,
	ShrimpIcon,
	ShrubIcon,
	SkullIcon,
	SnowflakeIcon,
	SofaIcon,
	SpeakerIcon,
	SproutIcon,
	SquirrelIcon,
	StethoscopeIcon,
	StoreIcon,
	SunIcon,
	TagIcon,
	TentTreeIcon,
	TheaterIcon,
	TractorIcon,
	TreePineIcon,
	TruckIcon,
	TurtleIcon,
	UmbrellaIcon,
	UtensilsIcon,
	WalletIcon,
	WheatIcon,
	WrenchIcon,
} from 'lucide-react';
import React from 'react';

const categoryIcons = {
	'alarm-clock': <AlarmClockIcon />,
	album: <AlbumIcon />,
	ambulance: <AmbulanceIcon />,
	amphora: <AmphoraIcon />,
	anchor: <AnchorIcon />,
	antenna: <AntennaIcon />,
	anvil: <AnvilIcon />,
	apple: <AppleIcon />,
	archive: <ArchiveIcon />,
	armchair: <AwardIcon />,
	axe: <AxeIcon />,
	baby: <BabyIcon />,
	backpack: <BackpackIcon />,
	bananna: <BananaIcon />,
	bandage: <BandageIcon />,
	banknote: <BanknoteIcon />,
	bath: <BathIcon />,
	bean: <BeanIcon />,
	bed: <BedIcon />,
	beef: <BeefIcon />,
	beer: <BeerIcon />,
	'biceps-flexed': <BicepsFlexedIcon />,
	bike: <BikeIcon />,
	binoculars: <BinocularsIcon />,
	bird: <BirdIcon />,
	book: <BookIcon />,
	'boom-box': <BoomBoxIcon />,
	bot: <BoxIcon />,
	'bow-arrow': <BowArrowIcon />,
	brain: <BrainIcon />,
	briefcase: <BriefcaseIcon />,
	brush: <BrushIcon />,
	'brush-cleaning': <BrushCleaningIcon />,
	bubbles: <BubblesIcon />,
	bug: <BugIcon />,
	building: <BuildingIcon />,
	bus: <BusIcon />,
	cable: <CableIcon />,
	cake: <CakeIcon />,
	calculator: <CalculatorIcon />,
	camera: <CameraIcon />,
	candy: <CandyIcon />,
	'candy-cane': <CandyCaneIcon />,
	car: <CarIcon />,
	'car-front': <CarFrontIcon />,
	caravan: <CaravanIcon />,
	carrot: <CarrotIcon />,
	castle: <CastleIcon />,
	cat: <CatIcon />,
	'chef-hat': <ChefHatIcon />,
	cherry: <CherryIcon />,
	church: <ChurchIcon />,
	cigarette: <CigaretteIcon />,
	'circle-dashed': <CircleDashedIcon />,
	citrus: <CitrusIcon />,
	clapperboard: <ClapperboardIcon />,
	clipboard: <ClipboardIcon />,
	clock: <ClockIcon />,
	cloud: <CloudIcon />,
	clover: <CloverIcon />,
	coffee: <CoffeeIcon />,
	cookie: <CookieIcon />,
	croissant: <CroissantIcon />,
	dog: <DogIcon />,
	'door-closed': <DoorClosedIcon />,
	drama: <DramaIcon />,
	drill: <DrillIcon />,
	drum: <DrumIcon />,
	drumstick: <DrumstickIcon />,
	dumbbell: <DumbbellIcon />,
	earth: <EarthIcon />,
	ellipsis: <EllipsisIcon />,
	fuel: <FuelIcon />,
	gift: <GiftIcon />,
	gamepad: <Gamepad2Icon />,
	ghost: <GhostIcon />,
	'glass-water': <GlassWaterIcon />,
	guitar: <GuitarIcon />,
	ham: <HamIcon />,
	hamburger: <HamburgerIcon />,
	hammer: <HammerIcon />,
	'hat-glasses': <HatGlassesIcon />,
	headphones: <HeadphonesIcon />,
	heart: <HeartIcon />,
	hospital: <HospitalIcon />,
	hotel: <HotelIcon />,
	house: <HouseIcon />,
	'ice-cream-cone': <IceCreamConeIcon />,
	lamp: <LampIcon />,
	laptop: <LaptopIcon />,
	leaf: <LeafIcon />,
	lightbulb: <LightbulbIcon />,
	martini: <MartiniIcon />,
	medal: <MedalIcon />,
	mountain: <MountainSnowIcon />,
	newspaper: <NewspaperIcon />,
	package: <PackageIcon />,
	paintbrush: <PaintbrushIcon />,
	palette: <PaletteIcon />,
	'party-popper': <PartyPopperIcon />,
	'paw-print': <PawPrintIcon />,
	phone: <PhoneIcon />,
	piano: <PianoIcon />,
	pickaxe: <PickaxeIcon />,
	'piggy-bank': <PiggyBankIcon />,
	pizza: <PizzaIcon />,
	plane: <PlaneIcon />,
	'pocket-knife': <PocketKnifeIcon />,
	popcorn: <PopcornIcon />,
	popsicle: <PopsicleIcon />,
	printer: <PrinterIcon />,
	puzzle: <PuzzleIcon />,
	rabbit: <RabbitIcon />,
	rat: <RatIcon />,
	'receipt-text': <ReceiptTextIcon />,
	rocket: <RocketIcon />,
	'rocking-chair': <RockingChairIcon />,
	'roller-coaster': <RollerCoasterIcon />,
	// rose: <RoseIcon />,
	sailboat: <SailboatIcon />,
	salad: <SaladIcon />,
	sandwich: <SandwichIcon />,
	ship: <ShipIcon />,
	shirt: <ShirtIcon />,
	'shopping-bag': <ShoppingBagIcon />,
	'shopping-basket': <ShoppingBasketIcon />,
	'shopping-cart': <ShoppingCartIcon />,
	shovel: <ShovelIcon />,
	'shower-head': <ShowerHeadIcon />,
	shrimp: <ShrimpIcon />,
	shrub: <ShrubIcon />,
	skull: <SkullIcon />,
	snowflake: <SnowflakeIcon />,
	sofa: <SofaIcon />,
	speaker: <SpeakerIcon />,
	sprout: <SproutIcon />,
	squirrel: <SquirrelIcon />,
	stethoscope: <StethoscopeIcon />,
	store: <StoreIcon />,
	sun: <SunIcon />,
	tag: <TagIcon />,
	'tent-tree': <TentTreeIcon />,
	theater: <TheaterIcon />,
	tractor: <TractorIcon />,
	'tree-pine': <TreePineIcon />,
	truck: <TruckIcon />,
	turtle: <TurtleIcon />,
	umbrella: <UmbrellaIcon />,
	utensils: <UtensilsIcon />,
	wheat: <WheatIcon />,
	wrench: <WrenchIcon />,
	wallet: <WalletIcon />,
};
export type CategoryIconKey = keyof typeof categoryIcons;

const colorClassNames = {
	'blue-gray': 'bg-blue-gray-100 text-blue-gray-500',
	'warm-gray': 'bg-warm-gray-100 text-warm-gray-500',
	red: 'bg-red-100 text-red-500',
	orange: 'bg-orange-100 text-orange-500',
	amber: 'bg-amber-100 text-amber-500',
	yellow: 'bg-yellow-100 text-yellow-500',
	lime: 'bg-lime-100 text-lime-500',
	green: 'bg-green-100 text-green-500',
	emrald: 'bg-emrald-100 text-emrald-500',
	teal: 'bg-teal-100 text-teal-500',
	cyan: 'bg-cyan-100 text-cyan-500',
	'light-blue': 'bg-light-blue-100 text-light-blue-500',
	blue: 'bg-blue-100 text-blue-500',
	indigo: 'bg-indigo-100 text-indigo-500',
	violet: 'bg-violet-100 text-violet-500',
	purple: 'bg-purple-100 text-purple-500',
	fuschia: 'bg-fuschia-100 text-fuschia-500',
	pink: 'bg-pink-100 text-pink-500',
	rose: 'bg-rose-100 text-rose-500',
};
export type CategoryColorKey = keyof typeof colorClassNames;

type CategoryIconProps = Readonly<{
	icon: CategoryIconKey;
	color: CategoryColorKey;
	className?: string;
}>;

export default function CategoryIcon({ icon, color, className }: CategoryIconProps) {
	return (
		<div
			className={cn(
				'size-12 flex items-center justify-center shadow rounded-lg',
				colorClassNames[color],
				className,
			)}>
			{categoryIcons[icon]}
		</div>
	);
}
