import { cn } from '@/lib/utils';
import {
	AlarmClockIcon,
	AlbumIcon,
	AmbulanceIcon,
	AmphoraIcon,
	AnchorIcon,
	AntennaIcon,
	AnvilIcon,
	AppleIcon,
	ArchiveIcon,
	AwardIcon,
	AxeIcon,
	BabyIcon,
	BackpackIcon,
	BananaIcon,
	BandageIcon,
	BanknoteIcon,
	BathIcon,
	BeanIcon,
	BedIcon,
	BeefIcon,
	BeerIcon,
	BicepsFlexedIcon,
	BikeIcon,
	BinocularsIcon,
	BirdIcon,
	BookIcon,
	BoomBoxIcon,
	BowArrowIcon,
	BoxIcon,
	BrainIcon,
	BriefcaseIcon,
	BrushCleaningIcon,
	BrushIcon,
	BubblesIcon,
	BugIcon,
	BuildingIcon,
	BusIcon,
	CableIcon,
	CakeIcon,
	CalculatorIcon,
	CameraIcon,
	CandyCaneIcon,
	CandyIcon,
	CaravanIcon,
	CarFrontIcon,
	CarIcon,
	CarrotIcon,
	CastleIcon,
	CatIcon,
	ChefHatIcon,
	CherryIcon,
	ChurchIcon,
	CigaretteIcon,
	CircleDashedIcon,
	CitrusIcon,
	ClapperboardIcon,
	ClipboardIcon,
	ClockIcon,
	CloudIcon,
	CloverIcon,
	CoffeeIcon,
	CookieIcon,
	CroissantIcon,
	DogIcon,
	DoorClosedIcon,
	DramaIcon,
	DrillIcon,
	DrumIcon,
	DrumstickIcon,
	DumbbellIcon,
	EarthIcon,
	EllipsisIcon,
	FuelIcon,
	Gamepad2Icon,
	GhostIcon,
	GiftIcon,
	GlassWaterIcon,
	GuitarIcon,
	HamburgerIcon,
	HamIcon,
	HammerIcon,
	HatGlassesIcon,
	HeadphonesIcon,
	HeartIcon,
	HospitalIcon,
	HotelIcon,
	HouseIcon,
	IceCreamConeIcon,
	LampIcon,
	LaptopIcon,
	LeafIcon,
	LightbulbIcon,
	MartiniIcon,
	MedalIcon,
	MountainSnowIcon,
	NewspaperIcon,
	PackageIcon,
	PaintbrushIcon,
	PaletteIcon,
	PartyPopperIcon,
	PawPrintIcon,
	PhoneIcon,
	PianoIcon,
	PickaxeIcon,
	PiggyBankIcon,
	PizzaIcon,
	PlaneIcon,
	PocketKnifeIcon,
	PopcornIcon,
	PopsicleIcon,
	PrinterIcon,
	PuzzleIcon,
	RabbitIcon,
	RatIcon,
	ReceiptTextIcon,
	RocketIcon,
	RockingChairIcon,
	RollerCoasterIcon,
	SailboatIcon,
	SaladIcon,
	SandwichIcon,
	ShipIcon,
	ShirtIcon,
	ShoppingBagIcon,
	ShoppingBasketIcon,
	ShoppingCartIcon,
	ShovelIcon,
	ShowerHeadIcon,
	ShrimpIcon,
	ShrubIcon,
	SkullIcon,
	SnowflakeIcon,
	SofaIcon,
	SpeakerIcon,
	SproutIcon,
	SquirrelIcon,
	StethoscopeIcon,
	StoreIcon,
	SunIcon,
	TagIcon,
	TentTreeIcon,
	TheaterIcon,
	TractorIcon,
	TreePineIcon,
	TruckIcon,
	TurtleIcon,
	UmbrellaIcon,
	UtensilsIcon,
	WalletIcon,
	WheatIcon,
	WrenchIcon,
} from 'lucide-react';
import React from 'react';

const categoryIcons = {
	'alarm-clock': <AlarmClockIcon className='size-55/100' />,
	album: <AlbumIcon className='size-55/100' />,
	ambulance: <AmbulanceIcon className='size-55/100' />,
	amphora: <AmphoraIcon className='size-55/100' />,
	anchor: <AnchorIcon className='size-55/100' />,
	antenna: <AntennaIcon className='size-55/100' />,
	anvil: <AnvilIcon className='size-55/100' />,
	apple: <AppleIcon className='size-55/100' />,
	archive: <ArchiveIcon className='size-55/100' />,
	armchair: <AwardIcon className='size-55/100' />,
	axe: <AxeIcon className='size-55/100' />,
	baby: <BabyIcon className='size-55/100' />,
	backpack: <BackpackIcon className='size-55/100' />,
	bananna: <BananaIcon className='size-55/100' />,
	bandage: <BandageIcon className='size-55/100' />,
	banknote: <BanknoteIcon className='size-55/100' />,
	bath: <BathIcon className='size-55/100' />,
	bean: <BeanIcon className='size-55/100' />,
	bed: <BedIcon className='size-55/100' />,
	beef: <BeefIcon className='size-55/100' />,
	beer: <BeerIcon className='size-55/100' />,
	'biceps-flexed': <BicepsFlexedIcon className='size-55/100' />,
	bike: <BikeIcon className='size-55/100' />,
	binoculars: <BinocularsIcon className='size-55/100' />,
	bird: <BirdIcon className='size-55/100' />,
	book: <BookIcon className='size-55/100' />,
	'boom-box': <BoomBoxIcon className='size-55/100' />,
	bot: <BoxIcon className='size-55/100' />,
	'bow-arrow': <BowArrowIcon className='size-55/100' />,
	brain: <BrainIcon className='size-55/100' />,
	briefcase: <BriefcaseIcon className='size-55/100' />,
	brush: <BrushIcon className='size-55/100' />,
	'brush-cleaning': <BrushCleaningIcon className='size-55/100' />,
	bubbles: <BubblesIcon className='size-55/100' />,
	bug: <BugIcon className='size-55/100' />,
	building: <BuildingIcon className='size-55/100' />,
	bus: <BusIcon className='size-55/100' />,
	cable: <CableIcon className='size-55/100' />,
	cake: <CakeIcon className='size-55/100' />,
	calculator: <CalculatorIcon className='size-55/100' />,
	camera: <CameraIcon className='size-55/100' />,
	candy: <CandyIcon className='size-55/100' />,
	'candy-cane': <CandyCaneIcon className='size-55/100' />,
	car: <CarIcon className='size-55/100' />,
	'car-front': <CarFrontIcon className='size-55/100' />,
	caravan: <CaravanIcon className='size-55/100' />,
	carrot: <CarrotIcon className='size-55/100' />,
	castle: <CastleIcon className='size-55/100' />,
	cat: <CatIcon className='size-55/100' />,
	'chef-hat': <ChefHatIcon className='size-55/100' />,
	cherry: <CherryIcon className='size-55/100' />,
	church: <ChurchIcon className='size-55/100' />,
	cigarette: <CigaretteIcon className='size-55/100' />,
	'circle-dashed': <CircleDashedIcon className='size-55/100' />,
	citrus: <CitrusIcon className='size-55/100' />,
	clapperboard: <ClapperboardIcon className='size-55/100' />,
	clipboard: <ClipboardIcon className='size-55/100' />,
	clock: <ClockIcon className='size-55/100' />,
	cloud: <CloudIcon className='size-55/100' />,
	clover: <CloverIcon className='size-55/100' />,
	coffee: <CoffeeIcon className='size-55/100' />,
	cookie: <CookieIcon className='size-55/100' />,
	croissant: <CroissantIcon className='size-55/100' />,
	dog: <DogIcon className='size-55/100' />,
	'door-closed': <DoorClosedIcon className='size-55/100' />,
	drama: <DramaIcon className='size-55/100' />,
	drill: <DrillIcon className='size-55/100' />,
	drum: <DrumIcon className='size-55/100' />,
	drumstick: <DrumstickIcon className='size-55/100' />,
	dumbbell: <DumbbellIcon className='size-55/100' />,
	earth: <EarthIcon className='size-55/100' />,
	ellipsis: <EllipsisIcon className='size-55/100' />,
	fuel: <FuelIcon className='size-55/100' />,
	gift: <GiftIcon className='size-55/100' />,
	gamepad: <Gamepad2Icon className='size-55/100' />,
	ghost: <GhostIcon className='size-55/100' />,
	'glass-water': <GlassWaterIcon className='size-55/100' />,
	guitar: <GuitarIcon className='size-55/100' />,
	ham: <HamIcon className='size-55/100' />,
	hamburger: <HamburgerIcon className='size-55/100' />,
	hammer: <HammerIcon className='size-55/100' />,
	'hat-glasses': <HatGlassesIcon className='size-55/100' />,
	headphones: <HeadphonesIcon className='size-55/100' />,
	heart: <HeartIcon className='size-55/100' />,
	hospital: <HospitalIcon className='size-55/100' />,
	hotel: <HotelIcon className='size-55/100' />,
	house: <HouseIcon className='size-55/100' />,
	'ice-cream-cone': <IceCreamConeIcon className='size-55/100' />,
	lamp: <LampIcon className='size-55/100' />,
	laptop: <LaptopIcon className='size-55/100' />,
	leaf: <LeafIcon className='size-55/100' />,
	lightbulb: <LightbulbIcon className='size-55/100' />,
	martini: <MartiniIcon className='size-55/100' />,
	medal: <MedalIcon className='size-55/100' />,
	mountain: <MountainSnowIcon className='size-55/100' />,
	newspaper: <NewspaperIcon className='size-55/100' />,
	package: <PackageIcon className='size-55/100' />,
	paintbrush: <PaintbrushIcon className='size-55/100' />,
	palette: <PaletteIcon className='size-55/100' />,
	'party-popper': <PartyPopperIcon className='size-55/100' />,
	'paw-print': <PawPrintIcon className='size-55/100' />,
	phone: <PhoneIcon className='size-55/100' />,
	piano: <PianoIcon className='size-55/100' />,
	pickaxe: <PickaxeIcon className='size-55/100' />,
	'piggy-bank': <PiggyBankIcon className='size-55/100' />,
	pizza: <PizzaIcon className='size-55/100' />,
	plane: <PlaneIcon className='size-55/100' />,
	'pocket-knife': <PocketKnifeIcon className='size-55/100' />,
	popcorn: <PopcornIcon className='size-55/100' />,
	popsicle: <PopsicleIcon className='size-55/100' />,
	printer: <PrinterIcon className='size-55/100' />,
	puzzle: <PuzzleIcon className='size-55/100' />,
	rabbit: <RabbitIcon className='size-55/100' />,
	rat: <RatIcon className='size-55/100' />,
	'receipt-text': <ReceiptTextIcon className='size-55/100' />,
	rocket: <RocketIcon className='size-55/100' />,
	'rocking-chair': <RockingChairIcon className='size-55/100' />,
	'roller-coaster': <RollerCoasterIcon className='size-55/100' />,
	// rose: <RoseIcon className='size-55/100' />,
	sailboat: <SailboatIcon className='size-55/100' />,
	salad: <SaladIcon className='size-55/100' />,
	sandwich: <SandwichIcon className='size-55/100' />,
	ship: <ShipIcon className='size-55/100' />,
	shirt: <ShirtIcon className='size-55/100' />,
	'shopping-bag': <ShoppingBagIcon className='size-55/100' />,
	'shopping-basket': <ShoppingBasketIcon className='size-55/100' />,
	'shopping-cart': <ShoppingCartIcon className='size-55/100' />,
	shovel: <ShovelIcon className='size-55/100' />,
	'shower-head': <ShowerHeadIcon className='size-55/100' />,
	shrimp: <ShrimpIcon className='size-55/100' />,
	shrub: <ShrubIcon className='size-55/100' />,
	skull: <SkullIcon className='size-55/100' />,
	snowflake: <SnowflakeIcon className='size-55/100' />,
	sofa: <SofaIcon className='size-55/100' />,
	speaker: <SpeakerIcon className='size-55/100' />,
	sprout: <SproutIcon className='size-55/100' />,
	squirrel: <SquirrelIcon className='size-55/100' />,
	stethoscope: <StethoscopeIcon className='size-55/100' />,
	store: <StoreIcon className='size-55/100' />,
	sun: <SunIcon className='size-55/100' />,
	tag: <TagIcon className='size-55/100' />,
	'tent-tree': <TentTreeIcon className='size-55/100' />,
	theater: <TheaterIcon className='size-55/100' />,
	tractor: <TractorIcon className='size-55/100' />,
	'tree-pine': <TreePineIcon className='size-55/100' />,
	truck: <TruckIcon className='size-55/100' />,
	turtle: <TurtleIcon className='size-55/100' />,
	umbrella: <UmbrellaIcon className='size-55/100' />,
	utensils: <UtensilsIcon className='size-55/100' />,
	wheat: <WheatIcon className='size-55/100' />,
	wrench: <WrenchIcon className='size-55/100' />,
	wallet: <WalletIcon className='size-55/100' />,
};
export type CategoryIconKey = keyof typeof categoryIcons;

const colorClassNames = {
	'blue-gray': 'bg-blue-gray-100 text-blue-gray-500',
	'warm-gray': 'bg-warm-gray-100 text-warm-gray-500',
	red: 'bg-red-100 text-red-500',
	orange: 'bg-orange-100 text-orange-500',
	amber: 'bg-amber-100 text-amber-500',
	yellow: 'bg-yellow-100 text-yellow-500',
	lime: 'bg-lime-100 text-lime-500',
	green: 'bg-green-100 text-green-500',
	emerald: 'bg-emerald-100 text-emerald-500',
	teal: 'bg-teal-100 text-teal-500',
	cyan: 'bg-cyan-100 text-cyan-500',
	'light-blue': 'bg-light-blue-100 text-light-blue-500',
	blue: 'bg-blue-100 text-blue-500',
	indigo: 'bg-indigo-100 text-indigo-500',
	violet: 'bg-violet-100 text-violet-500',
	purple: 'bg-purple-100 text-purple-500',
	fuschia: 'bg-fuschia-100 text-fuschia-500',
	pink: 'bg-pink-100 text-pink-500',
	rose: 'bg-rose-100 text-rose-500',
};
export type CategoryColorKey = keyof typeof colorClassNames;

type CategoryIconProps = Readonly<{
	icon: CategoryIconKey;
	color: CategoryColorKey;
	className?: string;
}>;

export default function CategoryIcon({ icon, color, className }: CategoryIconProps) {
	return (
		<div
			className={cn(
				'size-12 flex items-center justify-center shadow rounded-lg',
				colorClassNames[color],
				className,
			)}>
			{categoryIcons[icon]}
		</div>
	);
}
